#!/usr/bin/env python3
"""Build the bundled scene for the splat-viewer app (numpy only).

There is no captured Gaussian-splat object available for the textbook yet,
so this script synthesises a small still life instead: a sphere, a torus,
and a cube standing on a plane that acts as a table. Splats are scattered
near the surface of each shape with randomised colour and scale, then
written out in the common ".splat" binary layout that phone capture apps
(and viewers such as antimatter15's splat viewer) use, so the bundled file
doubles as a worked example of the format:

    32 bytes per splat, little-endian:
      position   3 x float32   (x, y, z, world units)
      scale      3 x float32   (per-axis half-size-ish extent, world units)
      colour     4 x uint8     (r, g, b, a)
      rotation   4 x uint8     (a quaternion x, y, z, w, each packed as
                                 round(component * 128 + 128), 0..255)

The splat-viewer app renders every splat as an isotropic camera-facing
point sprite, so it never reads the rotation quaternion back out; it is
still written correctly (as the identity rotation here) so that the file
is a valid, complete example of the format for students who go on to open
it in another viewer, or who drag in their own capture.

Output: book/apps/splat-viewer/scene.splat, about 60 000 splats, under
2 MB (60 000 x 32 bytes = 1 920 000 bytes). Licence: the scene is
synthetic, generated by the course team, and released CC-BY-4.0, same as
the rest of the app.

Usage: python scripts/build-splat-viewer-data.py
"""
import io
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "book", "apps", "splat-viewer")
OUT_PATH = os.path.join(OUT_DIR, "scene.splat")

SEED = 20260906
MAX_BYTES = 2 * 1024 * 1024

# Splat counts per object, chosen to add up to about 60 000.
N_TABLE = 24000
N_SPHERE = 14000
N_TORUS = 12000
N_CUBE = 10000

SPLAT_DTYPE = np.dtype([
    ("position", "<f4", 3),
    ("scale", "<f4", 3),
    ("color", "u1", 4),
    ("rot", "u1", 4),
])

# Identity quaternion (x=0, y=0, z=0, w=1) packed into the format's uint8
# scheme, byte = round(component * 128 + 128) clamped to 0..255.
IDENTITY_ROT = np.array([128, 128, 128, 255], dtype=np.uint8)


def hsv_to_rgb(h, s, v):
    """Vectorised HSV -> RGB, all arrays in 0..1, returns (r, g, b) in 0..1."""
    h = np.mod(h, 1.0) * 6.0
    i = np.floor(h).astype(np.int32)
    f = h - i
    p = v * (1.0 - s)
    q = v * (1.0 - s * f)
    t = v * (1.0 - s * (1.0 - f))
    i = i % 6

    r = np.select(
        [i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
        [v, q, p, p, t, v],
    )
    g = np.select(
        [i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
        [t, v, v, q, p, p],
    )
    b = np.select(
        [i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
        [p, p, t, v, v, q],
    )
    return r, g, b


def make_colors(rng, n, base_hue, hue_jitter, sat_range, val_range, alpha_range):
    hue = base_hue + rng.uniform(-hue_jitter, hue_jitter, n)
    sat = rng.uniform(sat_range[0], sat_range[1], n)
    val = rng.uniform(val_range[0], val_range[1], n)
    r, g, b = hsv_to_rgb(hue, sat, val)
    alpha = rng.uniform(alpha_range[0], alpha_range[1], n)
    rgba = np.stack([r, g, b, alpha / 255.0], axis=1) * 255.0
    return np.clip(np.round(rgba), 0, 255).astype(np.uint8)


def make_table(rng, n, half_size, y0, thickness):
    x = rng.uniform(-half_size, half_size, n)
    z = rng.uniform(-half_size, half_size, n)
    y = y0 + rng.uniform(-thickness, thickness, n)
    pos = np.stack([x, y, z], axis=1).astype(np.float32)

    sx = rng.uniform(0.02, 0.045, n)
    sz = rng.uniform(0.02, 0.045, n)
    sy = rng.uniform(0.004, 0.012, n)
    scale = np.stack([sx, sy, sz], axis=1).astype(np.float32)

    color = make_colors(rng, n, base_hue=0.08, hue_jitter=0.02,
                         sat_range=(0.35, 0.55), val_range=(0.35, 0.55),
                         alpha_range=(220, 255))
    return pos, scale, color


def make_sphere(rng, n, center, radius, splat_size):
    v = rng.normal(size=(n, 3))
    v /= np.linalg.norm(v, axis=1, keepdims=True)
    jitter = rng.uniform(-0.02, 0.02, n) * radius
    pos = center + v * (radius + jitter[:, None])
    pos = pos.astype(np.float32)

    scale = rng.uniform(splat_size * 0.6, splat_size * 1.4, (n, 3)).astype(np.float32)
    color = make_colors(rng, n, base_hue=0.98, hue_jitter=0.04,
                         sat_range=(0.55, 0.85), val_range=(0.55, 0.9),
                         alpha_range=(210, 255))
    return pos, scale, color


def make_torus(rng, n, center, major_r, minor_r, splat_size):
    theta = rng.uniform(0, 2 * np.pi, n)   # around the ring
    phi = rng.uniform(0, 2 * np.pi, n)     # around the tube
    jitter = rng.uniform(-0.15, 0.15, n) * minor_r
    r_tube = minor_r + jitter
    x = (major_r + r_tube * np.cos(phi)) * np.cos(theta)
    z = (major_r + r_tube * np.cos(phi)) * np.sin(theta)
    y = r_tube * np.sin(phi)
    pos = center + np.stack([x, y, z], axis=1)
    pos = pos.astype(np.float32)

    scale = rng.uniform(splat_size * 0.6, splat_size * 1.4, (n, 3)).astype(np.float32)
    color = make_colors(rng, n, base_hue=0.55, hue_jitter=0.05,
                         sat_range=(0.5, 0.8), val_range=(0.55, 0.85),
                         alpha_range=(210, 255))
    return pos, scale, color


def make_cube(rng, n, center, half_size, splat_size):
    # Scatter over the six faces of a cube, roughly evenly by area.
    face = rng.integers(0, 6, n)
    u = rng.uniform(-half_size, half_size, n)
    v = rng.uniform(-half_size, half_size, n)
    jitter = rng.uniform(-0.02, 0.02, n) * half_size

    x = np.zeros(n)
    y = np.zeros(n)
    z = np.zeros(n)

    m = face == 0  # +x
    x[m], y[m], z[m] = half_size + jitter[m], u[m], v[m]
    m = face == 1  # -x
    x[m], y[m], z[m] = -half_size + jitter[m], u[m], v[m]
    m = face == 2  # +y
    x[m], y[m], z[m] = u[m], half_size + jitter[m], v[m]
    m = face == 3  # -y
    x[m], y[m], z[m] = u[m], -half_size + jitter[m], v[m]
    m = face == 4  # +z
    x[m], y[m], z[m] = u[m], v[m], half_size + jitter[m]
    m = face == 5  # -z
    x[m], y[m], z[m] = u[m], v[m], -half_size + jitter[m]

    pos = center + np.stack([x, y, z], axis=1)
    pos = pos.astype(np.float32)

    scale = rng.uniform(splat_size * 0.6, splat_size * 1.4, (n, 3)).astype(np.float32)
    color = make_colors(rng, n, base_hue=0.30, hue_jitter=0.05,
                         sat_range=(0.45, 0.75), val_range=(0.55, 0.85),
                         alpha_range=(210, 255))
    return pos, scale, color


def main():
    rng = np.random.default_rng(SEED)

    table_half = 2.0
    table_y = 0.0

    sphere_r = 0.6
    sphere_center = np.array([-1.15, table_y + sphere_r, 0.65])

    torus_major, torus_minor = 0.5, 0.16
    torus_center = np.array([1.1, table_y + torus_minor, -0.35])

    cube_half = 0.38
    cube_center = np.array([0.05, table_y + cube_half, -1.15])

    table_pos, table_scale, table_color = make_table(
        rng, N_TABLE, table_half, table_y, thickness=0.01
    )
    sphere_pos, sphere_scale, sphere_color = make_sphere(
        rng, N_SPHERE, sphere_center, sphere_r, splat_size=0.028
    )
    torus_pos, torus_scale, torus_color = make_torus(
        rng, N_TORUS, torus_center, torus_major, torus_minor, splat_size=0.022
    )
    cube_pos, cube_scale, cube_color = make_cube(
        rng, N_CUBE, cube_center, cube_half, splat_size=0.024
    )

    n_total = N_TABLE + N_SPHERE + N_TORUS + N_CUBE
    splats = np.zeros(n_total, dtype=SPLAT_DTYPE)

    parts = [
        (table_pos, table_scale, table_color),
        (sphere_pos, sphere_scale, sphere_color),
        (torus_pos, torus_scale, torus_color),
        (cube_pos, cube_scale, cube_color),
    ]
    offset = 0
    for pos, scale, color in parts:
        n = pos.shape[0]
        splats["position"][offset:offset + n] = pos
        splats["scale"][offset:offset + n] = scale
        splats["color"][offset:offset + n] = color
        splats["rot"][offset:offset + n] = IDENTITY_ROT
        offset += n

    # Shuffle so no viewer can assume spatial structure from file order.
    rng.shuffle(splats)

    os.makedirs(OUT_DIR, exist_ok=True)
    with io.open(OUT_PATH, "wb") as f:
        f.write(splats.tobytes())

    size = os.path.getsize(OUT_PATH)
    print(
        "Wrote {} splats ({} bytes) to {}".format(n_total, size, OUT_PATH),
        file=sys.stderr,
    )
    if size > MAX_BYTES:
        print(
            "ERROR: scene.splat is {} bytes, over the {} byte limit".format(
                size, MAX_BYTES
            ),
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
